#!/bin/bash
export DASHSCOPE_API_KEY=sk-a71a0e94b4854adaa8d34a148d4253d7
export DB_URL="jdbc:mysql://localhost:3306/chronoflow?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8"
export DB_USERNAME=root
export DB_PASSWORD=root123
export REDIS_HOST=localhost
export REDIS_PORT=6379
export JWT_SECRET=chronoflow-production-2026-32bytes!!
export SERVER_PORT=8080
export ALIYUN_SMS_ACCESS_KEY_ID=LTAI5t6mZCkn4wEjHXvzUeAG
export ALIYUN_SMS_ACCESS_KEY_SECRET=NtmRq1XxJYreiFn6IK8pgn6cupavTE
export ALIYUN_SMS_SIGN_NAME=舟山市时纪云
export ALIYUN_SMS_TEMPLATE_CODE=SMS_327868154
export ALIYUN_DM_ACCESS_KEY_ID=LTAI5t6mZCkn4wEjHXvzUeAG
export ALIYUN_DM_ACCESS_KEY_SECRET=NtmRq1XxJYreiFn6IK8pgn6cupavTE
export ALIYUN_DM_ACCOUNT_NAME=noreply@xaxinan.top
export ALIYUN_DM_FROM_ALIAS=时纪流
export ALIYUN_GREEN_ACCESS_KEY_ID=LTAI5t7BKRhYvKe8Q9rz1JHF
export ALIYUN_GREEN_ACCESS_KEY_SECRET=W5CHdqXiylUlrgxEfbF22RQsXZQJ5U
export ALIYUN_CLOUDAUTH_ACCESS_KEY_ID=LTAI5t6mZCkn4wEjHXvzUeAG
export ALIYUN_CLOUDAUTH_ACCESS_KEY_SECRET=NtmRq1XxJYreiFn6IK8pgn6cupavTE
export ALIYUN_CLOUDAUTH_SCENE_ID=1000018914
exec java -jar /app/chronoflow.jar
